services:
  postgres-db:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      DB_HOST: postgres-db    
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  user-service:
    build: ./user-service
    container_name: user-service
    depends_on:
      - postgres-db
    environment:
      DATABASE_URL: postgresql://postgres:admin@postgres-db:5432/postgres
    ports:
      - "8085:8085"

  role-service:
    build: ./role-service
    container_name: role-service
    depends_on:
      - postgres-db
    environment:
      DATABASE_URL: postgresql://postgres:admin@postgres-db:5432/postgres
    ports:
      - "8082:8082"


  dept-service:
    build: ./dept-service
    container_name: dept-service
    depends_on:
      - postgres-db
    environment:
      DATABASE_URL: postgresql://postgres:admin@postgres-db:5432/postgres
    ports:
      - "8086:8086"


      
  country-service:
    build: ./country-service
    container_name: country-service
    depends_on:
      - postgres-db
    environment:
      DATABASE_URL: postgresql://postgres:admin@postgres-db:5432/postgres
    ports:
      - "8087:8087"


  state-service:
    build: ./state-service
    container_name: state-service
    depends_on:
      - postgres-db
    environment:
      DATABASE_URL: postgresql://postgres:admin@postgres-db:5432/postgres
    ports:
      - "8088:8088"





  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      - user-service
      - role-service
      - dept-service
      - country-service
      - state-service 
    ports:
      - "3000:3000"
